Optional JIRA task
digitalroute/cz-conventional-changelog-for-jira pull request #21
Opened 2021-01-21 15:07 UTC by two-legs

We have a case where there is not always a task in JIRA, so it would be great to be able to make the field with JIRA optional.

2021-02-03 13:52 UTC, polarn commented
Sorry for being super slow.. May I ask why you use this module if you don't have any Jira issue? :)

2021-02-03 13:57 UTC, two-legs commented
@polarn We have a JIRA task in most cases, but we have exceptions. These may be some very small changes that we don't create tasks for.

2021-02-03 14:00 UTC, polarn commented
Allright understand. And you don't change the default behaviour so it should be fine! Can you rebase it and make it into one single commit? Because I see my and Julius commits in the git log of this branch?

2021-02-03 14:07 UTC, two-legs commented
Done

2021-02-03 17:49 UTC, polarn commented
Then I try it I get this:
```
?  (optional) (DAZ-5642)
```

And before it was like:
```
? Enter JIRA issue (DAZ-12345) (DAZ-5642)
```

Haven't had time to check the code much, do you get it working correctly when you test it? Seems like the message created is not correct...

2021-02-04 08:28 UTC, two-legs commented
Looks like the formatter broke the code after fix... 
I fixed and added tests for dynamic questions. Also I fixed similar bug with the scope question.

2021-02-04 17:32 UTC, polarn requested changes
Classic copy and paste miss. 😄

2021-02-04 17:32 UTC, polarn commented on index.js
> +    config.jiraMode,
@two-legs this line and the next you need to replace `jiraMode` with `jiraOptional` 😉

2021-02-04 18:08 UTC, two-legs commented on index.js
> +    config.jiraMode,
Fixed

2021-02-04 19:21 UTC, merged

2021-02-04 19:22 UTC, polarn commented
Thanks for contributing! Next time I'll try to be faster...

2021-02-04 21:16 UTC, polarn commented
:tada: This PR is included in version 6.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@digitalroute/cz-conventional-changelog-for-jira)
- [GitHub release](https://github.com/digitalroute/cz-conventional-changelog-for-jira/releases/tag/v6.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: