New jiraLocation option for "footer"
digitalroute/cz-conventional-changelog-for-jira pull request #55
Opened 2022-02-15 15:38 UTC by antodd

This request is an effort to format the commit message so they better align with the https://github.com/semantic-release/release-notes-generator plugin for semantic-release.  This is allow the semantic-release plugin to find the Jira ID in the footer of the commit message and build the appropriate links back to Jira in the release nots.

2022-02-16 07:59 UTC, juliuscc commented
Hi @antodd! I think your PR is very related to this issue: #31 Would you say that it's any different than using the option `jiraLocation: 'post-description'`?

2022-02-16 08:00 UTC, juliuscc commented
If not then we should improve our docs so that it's easier to find that option.

2022-02-16 14:24 UTC, antodd commented
@juliuscc I should have provided some examples:

This PR will put the Jira ID in the footer of the commit message with a double newline between the subject and the footer.  It also account for an optional body. 

```
feat: this is a commit message

JIRA-1001
```

or 

```
feat: this is a commit message

this is a longer commit body for yadda yadda yadda

JIRA-1001
```

The current options for `jiraLocation` are:
`pre-type`: `JIRA-1000 type(scope): this is a commit message`

`pre-description`: `type(scope): JIRA-1000 this is a commit message`

`post-description`: `type(scope): this is a commit message JIRA-1000`

2022-02-17 18:51 UTC, juliuscc commented
Ah, I see. Would it make sense to call this option `post-body` for consistency, or do you think that is more confusing than `footer`? 

Secondly, could you add your contributions to the documentation? Preferably with examples like you have shared here. 😁 

What do you think about this feature @Saeger? Is it in the scope of the package?

If @Saeger is happy with the feature and you address the two points I raised, I think this is a great addition!

2022-02-18 08:43 UTC, Saeger requested changes
As mentioned in the PR, can we get a better naming for the feature and improved documentation?

2022-02-21 16:41 UTC, antodd commented
@juliuscc @Saeger I've pushed the changes you requested

2022-02-21 17:28 UTC, Saeger approved these changes
LGTM

2022-02-22 08:22 UTC, juliuscc commented on README.md
> +```
This is a great addition to the docs! Thanks @antodd! ❤️

2022-02-22 08:22 UTC, juliuscc approved these changes

2022-02-22 08:23 UTC, merged